// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackerExpense.Server.Data;

#nullable disable

namespace TrackerExpense.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241128201122_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TrackerExpense.Shared.Models.ExpenseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10.0m,
                            CreatedAt = new DateTime(2024, 11, 28, 20, 11, 22, 530, DateTimeKind.Utc).AddTicks(8064),
                            Description = "",
                            Title = "Bought a Snack"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.0m,
                            CreatedAt = new DateTime(2024, 11, 28, 21, 11, 22, 530, DateTimeKind.Utc).AddTicks(8067),
                            Description = "",
                            Title = "Bought a phone"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20.0m,
                            CreatedAt = new DateTime(2024, 11, 28, 22, 11, 22, 530, DateTimeKind.Utc).AddTicks(8072),
                            Description = "",
                            Title = "Bought Lunch"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
