// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackerExpense.Server.Data;

#nullable disable

namespace TrackerExpense.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class TrackerExpenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TrackerExpense.Shared.Models.ExpenseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 65.0m,
                            CreatedAt = new DateTime(2024, 11, 29, 12, 55, 37, 363, DateTimeKind.Utc).AddTicks(595),
                            Description = "Petrol at Tesco",
                            Title = "Transport"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3.6m,
                            CreatedAt = new DateTime(2024, 11, 29, 13, 55, 37, 363, DateTimeKind.Utc).AddTicks(598),
                            Description = "Meal deal from Tesco for lunch",
                            Title = "Eating out"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 84.32m,
                            CreatedAt = new DateTime(2024, 11, 29, 14, 55, 37, 363, DateTimeKind.Utc).AddTicks(603),
                            Description = "Weekly shop - Tesco",
                            Title = "Groceries"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
